# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 01:06
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars'),
        ),
    ]
